name: First workflow
on: workflow_dispatch
jobs:
  First_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Good Morning
        run: echo "HI Harsha Parsha"
      - name: print good bye
        run: echo "Bye ğŸ§"
